let deportes_lista = {
    1: "fútbol",
    2: "vóleyball",
    3: "Clavados",
    4: "Natación",
    5: "Natación artística",
    6: "Polo acuático",
    7: "Natación en Aguas abiertas",
    8: "Maratón",
    9: "Marcha",
    10: "Atletismo",
    11: "Bádminton",
    12: "Balonmano",
    13: "Básquetbol",
    14: "Básquetbol 3x3",
    15: "Béisbol",
    16: "Boxeo",
    17: "Bowling",
    18: "Breaking",
    19: "Canotaje Slalom",
    20: "Canotaje de velocidad",
    21: "BMX Freestyle",
    22: "BMX Racing",
    23: "Mountain Bike",
    24: "Ciclismo pista",
    25: "Ciclismo ruta",
    26: "Adiestramiento ecuestre",
    27: "Evento completo ecuestre",
    28: "Salto ecuestre",
    29: "Escalada deportiva",
    30: "Esgrima",
    31: "Esquí acuático y Wakeboard",
    32: "Gimnasia artística Masculina",
    33: "Gimnasia artística Femenina",
    34: "Gimnasia rítmica",
    35: "Gimnasia trampolín",
    36: "Golf",
    37: "Hockey césped",
    38: "Judo",
    39: "Karate",
    40: "Levantamiento de pesas",
    41: "Lucha",
    42: "Patinaje artístico",
    43: "Skateboarding",
    44: "Patinaje velocidad",
    45: "Pelota vasca",
    46: "Pentatlón moderno",
    47: "Racquetball",
    48: "Remo",
    49: "Rugby 7",
    50: "Sóftbol",
    51: "Squash",
    52: "Surf",
    53: "Taekwondo",
    54: "Tenis",
    55: "Tenis de mesa",
    56: "Tiro",
    57: "Tiro con arco",
    58: "Triatlón",
    59: "Vela",
    60: "Vóleibol",
    61: "Vóleibol playa"
};

